repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: debug-statements
      - id: detect-private-key
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
